# on pr
# build code
# lint code
# test code

name: Must run on custom runner

on: push

jobs:
  init:
    runs-on: self-hosted
    steps:
      - run: echo 'hello cloud gurus'
      - run: echo $HOSTNAME
