# on pr
# build code
# lint code
# test code

name: Build application code

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
